// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions not configured for linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions not supported.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYGCz_EDsJw8OmQjUNhJ5pAUeZS2Az3M',
    appId: '1:1089105014228:web:6173f3b99525f87a17fa41',
    messagingSenderId: '1089105014228',
    projectId: 'inventory-8cfd8',
    authDomain: 'inventory-8cfd8.firebaseapp.com',
    storageBucket: 'inventory-8cfd8.firebasestorage.app',
    measurementId: 'G-8BHYZ31E59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQOstGVOYn4UJVNKYCIJTEbtfaUczYqA',
    appId: '1:1089105014228:android:8146a755cda87af617fa41',
    messagingSenderId: '1089105014228',
    projectId: 'inventory-8cfd8',
    storageBucket: 'inventory-8cfd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiO7jiKnNqThrnm_j_4Wv95Mko1f4wQE',
    appId: '1:1089105014228:ios:09912d8bcfecb71917fa41',
    messagingSenderId: '1089105014228',
    projectId: 'inventory-8cfd8',
    storageBucket: 'inventory-8cfd8.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = ios;
  
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnYGCz_EDsJw8OmQjUNhJ5pAUeZS2Az3M',
    appId: '1:1089105014228:web:6a9692424ef996f517fa41',
    messagingSenderId: '1089105014228',
    projectId: 'inventory-8cfd8',
    authDomain: 'inventory-8cfd8.firebaseapp.com',
    storageBucket: 'inventory-8cfd8.firebasestorage.app',
    measurementId: 'G-WDZ4VHZFDP',
  );
}
