import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shadcn_ui/shadcn_ui.dart';
import 'package:firebase_core/firebase_core.dart';

import 'controllers/inventory_controller.dart';
import 'providers/inventory_provider.dart';
import 'views/home_screen.dart';
import 'firebase_options.dart'; // ← Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //  Initialize Firebase with options for all platforms
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Inventory controller + provider
  final controller = InventoryController();
  final inventoryProvider = InventoryProvider(controller);  //holds state and also the logic
  await inventoryProvider.initialize();    //initializing of the data 

  runApp(MyApp(inventoryProvider: inventoryProvider));
}

class MyApp extends StatelessWidget {
  final InventoryProvider inventoryProvider;

  const MyApp({super.key, required this.inventoryProvider});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
      value: inventoryProvider,        //for all screens were for this ,were calling of context.watch<InventoryProvider>()
      child: ShadApp.custom(
        themeMode: ThemeMode.light,
        appBuilder: (context) {
          return MaterialApp(
            title: 'Inventory Firebase',
            debugShowCheckedModeBanner: false,
            theme: Theme.of(context),
            builder: (context, child) => ShadAppBuilder(child: child!),
            home: const HomeScreen(),
          );
        },
      ),
    );
  }
}
